config/routes.rb
Rails.application.routes.draw do

  namespace :book do
    get "subject_select"
    get "chapter_select"
    get "interaction"
    get "page"
    get "page1"
    get "page2"

  end
  
  namespace :interactions do
    get "leaf"
    get "bee"
  end
  

  root 'application#index'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def index
    
  end
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  def subject_select
  end
  
  
  def chapter_select
  end
  
  def interaction
  end
  
  def page
  end
  def page1
  end
  def page2
  end

  
end

app/controllers/interactions_controller.rb
class InteractionsController < ApplicationController
  def leaf
  end
  
  
  def bee
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_back_to_root.html.haml
:scss
    #back-button{
        position: absolute;
        z-index: 100;
        top: 15px;
        left: 15px;
    }
    
= link_to root_path, id: "back-button", class: "btn btn-primary" do
    %span.glyphicon.glyphicon-chevron-left

app/views/application/index.html.haml
.container-fluid.np
    .col-xs-12.col-sm-6.np
        .panel.panel-primary
            .panel-heading 
                %b
                    Practicum 5
                Who is the fairest
            .panel-body
                %ul.list-group
                    %li.list-group-item 
                        = link_to book_subject_select_path do
                            %b #1
                            Subject Select
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                    %li.list-group-item 
                        = link_to book_chapter_select_path do
                            %b #2
                            Chapter Select
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                    %li.list-group-item 
                        = link_to book_interaction_path do
                            %b #2
                            Interaction
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                   
            .panel-footer
                CS160 - Intro to UI Design and Development
   

app/views/book/chapter_select.html.haml
= javascript_include_tag( 'chapter_select' )

.container-fluid
    %h1.title Select a Chapter
    
    .row
        .col-xs-4.col-xs-offset-4
            %img.chapter-img.col-xs-6{:src => "https://group2-final-beyhum.c9users.io/assets/leaf.png"}
            %img.chapter-img.col-xs-6{:src => "https://group2-final-beyhum.c9users.io/assets/leaf.png"}
            %img.chapter-img.col-xs-6{:src => "https://group2-final-beyhum.c9users.io/assets/leaf.png"}
            %img.chapter-img.col-xs-6{:src => "https://group2-final-beyhum.c9users.io/assets/leaf.png"}
    




:scss
    .title{
        text-align: center;
        margin-bottom: 10%
    }
    
    .chapter-img{
        max-width: 100%;
    }

app/views/book/interaction.html.haml
-# %img#fullscreen{:src => "https://group2-final-beyhum.c9users.io/assets/updated.png"}

#header
    %h1 Plant Biology
#main
    #content
        %h2 #Photosynthesis
        %p Photosynthesis is a process used by plants and other organisms to convert light energy into chemical energy that can later be released to fuel the organisms' activities (energy transformation). This chemical energy is stored in carbohydrate molecules, such as sugars, which are synthesized from carbon dioxide and water – hence the name photosynthesis, from the Greek φῶς, phōs, "light", and σύνθεσις, synthesis, "putting together". In most cases, oxygen is also released as a waste product. Most plants, most algae, and cyanobacteria perform photosynthesis; such organisms are called photoautotrophs. Photosynthesis is largely responsible for producing and maintaining the oxygen content of the Earth's atmosphere, and supplies all of the organic compounds and most of the energy necessary for life on Earth.
        %p Although photosynthesis is performed differently by different species, the process always begins when energy from light is absorbed by proteins called reaction centres that contain green chlorophyll pigments. In plants, these proteins are held inside organelles called chloroplasts, which are most abundant in leaf cells, while in bacteria they are embedded in the plasma membrane. In these light-dependent reactions, some energy is used to strip electrons from suitable substances, such as water, producing oxygen gas. The hydrogen freed by the splitting of water is used in the creation of two further compounds that act as an immediate energy storage means: reduced nicotinamide adenine dinucleotide phosphate (NADPH) and adenosine triphosphate (ATP), the "energy currency" of cells.
        %p In plants, algae and cyanobacteria, long-term energy storage in the form of sugars is produced by a subsequent sequence of light-independent reactions called the Calvin cycle; some bacteria use different mechanisms, such as the reverse Krebs cycle, to achieve the same end. In the Calvin cycle, atmospheric carbon dioxide is incorporated into already existing organic carbon compounds, such as ribulose bisphosphate (RuBP). Using the ATP and NADPH produced by the light-dependent reactions, the resulting compounds are then reduced and removed to form further carbohydrates, such as glucose.
        %p The first photosynthetic organisms probably evolved early in the evolutionary history of life and most likely used reducing agents such as hydrogen or hydrogen sulfide, rather than water, as sources of electrons. Cyanobacteria appeared later; the excess oxygen they produced contributed directly to the oxygenation of the Earth, which rendered the evolution of complex life possible. Today, the average rate of energy capture by photosynthesis globally is approximately 130 terawatts, which is about three times the current power consumption of human civilization. Photosynthetic organisms also convert around 100–115 thousand million metric tonnes of carbon into biomass per year.

:scss
    body{
        background-color: #dddddd
    }
    
    #fullscreen{
        width: 100%;
        height: 100%;
        opacity: .3;
        position: absolute;
    }
    
    #header{
        width: 100%;
        height: 10%;
        background-color: #333333;
        position: relative;
        
        text-align: center;
    }
    
    #main{
        margin: 0;
        width: 100%;
        background-color: #dddddd;
    }
    
    #content{
        width: 90%;
        margin: 5%;
        margin-top: 0%;
        margin-bottom: 0%;
    }
    
    h1{
        margin: 0;
        position: relative;
        top: 50%;
        transform: translateY(-50%); 
        color: #44aa44;
    }
    
    h2{
        margin: 0;
        padding-top: 5%;
        padding-bottom: 5%;
    }

app/views/book/page.html.haml
.container-fluid
    .row
        %img.chapter-img.col-xs-1.col-xs-offset-4{:src => "https://group2-final-beyhum.c9users.io/assets/leaf.png"}
        %h1.title.col-xs-4 Select a Chapter
            
    
    .row
        %h2#question.col-xs-10.col-xs-offset-1 QUESTION
    .row
        %h2#reading.col-xs-10.col-xs-offset-1 READING
    .row
        %h2#interaction.col-xs-10.col-xs-offset-1 INTERACTION
     
    




:scss
    .title{
        margin-bottom: 10%;
    }
    
    .chapter-img{
        max-width: 10%;
    }
    #question{
        background-color: #ffee75;
        color: white;
        text-align: center;
        height: 80px;
        padding-top: 10px;
    }
    
    #interaction{
        background-color: #ff5575;
        color: white;
        text-align: center;
        text-size: 5em;
        font-size: 5em;
    }
    
    #reading{
        border: 1px solid #dddddd;
        text-align: center;
        font-size: 8em;
        height: 400px;

    }

app/views/book/subject_select.html.haml
= javascript_include_tag( 'subject_select' )

.container-fluid
    %h1.title Select a Subject
    
    .row
        .col-xs-4.col-xs-offset-4
            %img.col-xs-6.subject-img{:src => "https://group2-final-beyhum.c9users.io/assets/science.png"}
            %img.col-xs-6.subject-img{:src => "https://group2-final-beyhum.c9users.io/assets/code.jpg"}
            %img.col-xs-6.subject-img{:src => "https://group2-final-beyhum.c9users.io/assets/leaf.png"}
            %img.col-xs-6.subject-img{:src => "https://group2-final-beyhum.c9users.io/assets/math.png"}





:scss
    .title{
        text-align: center;
        margin-bottom: 10%
    }
    
    .subject-img{
        max-width: 100%;

        text-align: center;
    }

app/views/interactions/leaf.html.haml
= javascript_include_tag( 'leaf' )
= javascript_include_tag( 'color_corrector' )

%script{:src => "https://code.jquery.com/ui/1.10.4/jquery-ui.js"}
%script{:src =>"//cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"}

#container-fluid
    %canvas#leaf-canvas.col-xs-11
    #controls.col-xs-12
        #slider-container
            #color-slider
            #slider-icons
                %img#autumn.slider-icon{:src => "https://group2-final-beyhum.c9users.io/assets/autumn.png"}
                %img#winter.slider-icon{:src => "https://group2-final-beyhum.c9users.io/assets/winter.png"}
                %img#spring.slider-icon{:src => "https://group2-final-beyhum.c9users.io/assets/spring.png"}
                %img#summer.slider-icon{:src => "https://group2-final-beyhum.c9users.io/assets/summer.png"}
        #photo-capture
            %button.capture-btn Take a photo of a leaf
            %input#input-upload{:type => "file", :accept => "image/*", :capture => "camera"}
        %canvas#mainCanvas


    
:coffeescript
    $ ->
        # Initialize paper canvas
        canvas = document.getElementById("mainCanvas")
        paper.setup(canvas)
        path = new paper.Path()
        path.strokeColor = 'black'
        point = new paper.Point(0, 50)
        path.moveTo(point)
        
        window.sunLight = 1;
        PEAK_HEIGHT = 35
        CYCLE_TIME = 500
        CYCLE_LENGTH = 100
        UPDATE_INTERVAL = 10
        # Already placed first point
        CURRENT_TIME = UPDATE_INTERVAL
        NEXT_POINT_X_OFFSET = CYCLE_LENGTH * UPDATE_INTERVAL / CYCLE_TIME
        

        setInterval(->
            point = point.add([NEXT_POINT_X_OFFSET, 0])
            
            # sunLight is the formula to calculate the amount of sun based on the day of the year and how much light the camera is picking up
            # lightLevel = 1
            # sunLight = lightLevel * 0.5 * (Math.cos( ((2 * Math.PI)/365) * (x + 180)) + 1) 
            
            # sunLight = (sunLight * lightLevel) Need to make lightLevel the sensor output from phone camera
            
            sunLight = 1
            path.lineTo(point.add([0, window.sunLight * PEAK_HEIGHT * Math.sin(CURRENT_TIME / CYCLE_TIME * 2 * Math.PI)]))
            
            CURRENT_TIME += UPDATE_INTERVAL
            if CURRENT_TIME > CYCLE_TIME
                CURRENT_TIME -= CYCLE_TIME
            
            if (path.bounds.width > paper.view.size.width + NEXT_POINT_X_OFFSET)
              #console.log("test")
              path.translate([-NEXT_POINT_X_OFFSET, 0])
              point = point.subtract([NEXT_POINT_X_OFFSET, 0])
              path.removeSegment(0)
        , UPDATE_INTERVAL)

:scss
    #slider-icons{
        text-align: left;
    }
    
    .slider-icon{
        max-width: 10%;
    }
    #autumn{
        margin-right: 17%;
    }
    #winter{
        margin-right: 22%;
    }
    #spring{
        margin-right: 15%;
    }
    #summer{
        margin-left: 0%;
    }
    
    #color-slider{
        /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#751717+0,ffffff+15,2784d1+33,ffffff+50,1cb52c+66,ffffff+85,e3e57b+100 */
        background: #751717; /* Old browsers */
        background: -moz-linear-gradient(left, #751717 0%, #ffffff 15%, #2784d1 33%, #ffffff 50%, #1cb52c 66%, #ffffff 85%, #e3e57b 100%); /* FF3.6-15 */
        background: -webkit-linear-gradient(left, #751717 0%,#ffffff 15%,#2784d1 33%,#ffffff 50%,#1cb52c 66%,#ffffff 85%,#e3e57b 100%); /* Chrome10-25,Safari5.1-6 */
        background: linear-gradient(to right, #751717 0%,#ffffff 15%,#2784d1 33%,#ffffff 50%,#1cb52c 66%,#ffffff 85%,#e3e57b 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#751717', endColorstr='#e3e57b',GradientType=1 ); /* IE6-9 */
    }
    
    #container-fluid{
        padding: 0px;
    }
    
    #controls{
        text-align: center;
        box-shadow: 0 -6px 10px rgba(0,0,0,0.19), 0 -6px 12px rgba(0,0,0,0.23);
        z-index: 2;
        width: 100%;
        background-color: #f7f7f7;
        

    }
    #controls > *{
        margin-top: 10px;
    }
    
    #photo-capture {
      position: relative;
      overflow: hidden;
      display: inline-block;
    }
    
    .capture-btn {
      border: 2px solid #44cc88;
      color: #44cc88;
      background-color: white;
      padding: 8px 20px;
      border-radius: 6px;
      font-size: 20px;
      font-weight: bold;
    }
    
    #input-upload {
      font-size: 100px;
      position: absolute;
      left: 0;
      top: 0;
      opacity: 0;
    }
    
    #leaf-canvas{
        width: 100%;
        background-color: #ededed

    }
    
    .hidden{
        display: none;
    }
    
    #mainCanvas{
        width: 100%;
        height: 100px;
        left: 0;
        border: 2px solid #44cc88;

    }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Workspace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    - controller = params[:controller]
    - if controller != 'application'
      = stylesheet_link_tag    controller, media: 'all', 'data-turbolinks-track' => true
      = javascript_include_tag controller, 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{name:"viewport", content: "user-scalable=no, width=device-width, initial-scale=1"}
    %script{:src =>"//cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"}

  %body
    = yield